import type { CategoryConfig } from "@/types/category"

const commonSeries = [
  "One Piece",
  "Dragon Ball",
  "Boku no Hero Academia",
  "My Hero Academia",
  "Kimetsu no Yaiba",
  "Demon Slayer",
  "Gotoubun no Hanayome",
  "Quintessential Quintuplets",
  "Evangelion",
  "Jujutsu Kaisen",
  "Re:Zero",
  "SPY x FAMILY",
  "Spy Family",
  "Tensei Shitara Slime",
  "That Time I Got Reincarnated as a Slime",
  "Naruto",
  "Attack on Titan",
  "Shingeki no Kyojin",
  "Tokyo Revengers",
  "Chainsaw Man",
  "Bleach",
  "Hunter x Hunter",
  "Mob Psycho",
  "Overlord",
  "Konosuba",
  "Fate",
  "Hololive",
  "Vtuber",
  "Pokemon",
  "Digimon",
  "Sailor Moon",
  "Cardcaptor Sakura",
  "Love Live",
  "Idolmaster",
  "Vocaloid",
  "Hatsune Miku",
]

export const categoryConfigs: Record<string, CategoryConfig> = {
  scale: {
    name: "Figuras Escala",
    slug: "scale",
    description: "Figuras de anime a escala 1/7, 1/8 y 1/4 de máxima calidad, importadas desde Japón. La mejor opción para coleccionistas en Perú que buscan el máximo detalle, pintura profesional y piezas de exhibición definitivas para su colección. Envío gratis a todo Perú.",
    badge: "📏 Figuras a escala 1/7, 1/8 y 1/4 • Detalle profesional",
    iconName: "Ruler",
    colors: {
      primary: "text-emerald-800",
      secondary: "text-emerald-600",
      gradient: "bg-gradient-to-b from-emerald-50 via-white to-teal-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-emerald-500",
    },
    searchTerms: ["scale", "Scale", "SCALE", "1/7", "1/8", "1/6", "1/4"],
    searchType: "scale",
    seriesList: commonSeries,
  },

  figma: {
    name: "Figma",
    slug: "figma",
    description: "Figuras de anime articuladas de Max Factory para coleccionistas en Perú. Los Figma ofrecen la máxima posabilidad con accesorios intercambiables, perfectos para fotografía y exhibición dinámica. Figuras originales importadas desde Japón con envío gratis a todo Perú.",
    badge: "🔧 Figuras articuladas de Max Factory • Accesorios intercambiables",
    iconName: "Settings",
    colors: {
      primary: "text-blue-800",
      secondary: "text-blue-600",
      gradient: "bg-gradient-to-b from-blue-50 via-white to-cyan-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-blue-500",
    },
    searchTerms: [
      "Figma",
      "figma",
      "FIGMA",
      "figma ",
      " figma",
      "Figma ",
      " Figma",
      "Max Factory",
      "Good Smile Company figma",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  figuarts: {
    name: "S.H.Figuarts",
    slug: "figuarts",
    description: "Figuras de anime de acción S.H.Figuarts de Bandai Tamashii Nations, con articulación superior y acabados premium. Ideal para coleccionistas en Perú de Dragon Ball, One Piece, Marvel y más. Originales importadas desde Japón con envío gratis.",
    badge: "⚔️ Figuras de acción Bandai • Dragon Ball, One Piece, Marvel",
    iconName: "Sword",
    colors: {
      primary: "text-red-800",
      secondary: "text-red-600",
      gradient: "bg-gradient-to-b from-red-50 via-white to-yellow-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-red-500",
    },
    searchTerms: [
      "S.H.Figuarts",
      "s.h.figuarts",
      "S.H.FIGUARTS",
      "Figuarts",
      "figuarts",
      "FIGUARTS",
      "S.H. Figuarts",
      "SH Figuarts",
      "sh figuarts",
      "SHFiguarts",
      "Bandai Figuarts",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  ichiban: {
    name: "Ichiban Kuji",
    slug: "ichiban",
    description: "Figuras de anime Ichiban Kuji originales de Banpresto, la lotería japonesa con premios exclusivos de tus series favoritas. Calidad superior a prize figures a precios accesibles. Importadas desde Japón para coleccionistas en Perú. Envío gratis.",
    badge: "🎰 Lotería japonesa Banpresto • Premios exclusivos",
    iconName: "Gift",
    colors: {
      primary: "text-orange-800",
      secondary: "text-orange-600",
      gradient: "bg-gradient-to-b from-orange-50 via-white to-red-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-orange-500",
    },
    searchTerms: [
      "Ichiban Kuji",
      "ichiban kuji",
      "ICHIBAN KUJI",
      "Ichiban",
      "ichiban",
      "ICHIBAN",
      "Kuji",
      "kuji",
      "KUJI",
      "Banpresto Ichiban",
      "一番くじ",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  plush: {
    name: "Plushies",
    slug: "plush",
    description: "Peluches de anime originales y suaves para coleccionar en Perú. Plushies oficiales de Pokemon, Sanrio, One Piece y más series populares. Perfectos como regalos o para decoración. Importados desde Japón con envío gratis a todo Perú.",
    badge: "🧸 Peluches originales • Pokemon, Sanrio, One Piece",
    iconName: "Heart",
    colors: {
      primary: "text-pink-800",
      secondary: "text-pink-600",
      gradient: "bg-gradient-to-b from-pink-50 via-white to-rose-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-pink-500",
    },
    searchTerms: [
      "plush",
      "plushie",
      "Plush",
      "Plushie",
      "PLUSH",
      "PLUSHIE",
      "peluche",
      "Peluche",
      "PELUCHE",
      "stuffed",
      "Stuffed",
      "soft toy",
    ],
    searchType: "name",
    seriesList: [...commonSeries, "Pokemon", "Sanrio", "Hello Kitty", "Rilakkuma", "Pusheen"],
  },

  popup: {
    name: "Pop Up Parade",
    slug: "popup",
    description: "Figuras de anime Pop Up Parade de Good Smile Company, la mejor relación calidad-precio del coleccionismo. Figuras de 17 cm con calidad de escala a precio de prize figure. Originales importadas desde Japón para coleccionistas en Perú con envío gratis.",
    badge: "⚡ Línea Good Smile Company • Mejor calidad-precio",
    iconName: "Zap",
    colors: {
      primary: "text-purple-800",
      secondary: "text-purple-600",
      gradient: "bg-gradient-to-b from-purple-50 via-white to-pink-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-purple-500",
    },
    searchTerms: [
      "Pop Up Parade",
      "pop up parade",
      "POP UP PARADE",
      "PopUp Parade",
      "popup parade",
      "POPUP PARADE",
      "Pop-Up Parade",
      "pop-up parade",
      "Good Smile Pop Up",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  nendoroid: {
    name: "Nendoroid",
    slug: "nendoroid",
    description: "Figuras de anime Nendoroid originales de Good Smile Company, el formato chibi más famoso del mundo. Figuras coleccionables con piezas intercambiables de One Piece, Demon Slayer, Jujutsu Kaisen y más. Importadas desde Japón para fans en Perú. Envío gratis.",
    badge: "😊 Nendoroid Good Smile • Partes intercambiables • Expresiones múltiples",
    iconName: "Smile",
    colors: {
      primary: "text-yellow-800",
      secondary: "text-yellow-600",
      gradient: "bg-gradient-to-b from-yellow-50 via-white to-orange-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-yellow-500",
    },
    searchTerms: [
      "Nendoroid",
      "nendoroid",
      "NENDOROID",
      "Nendoroid ",
      " Nendoroid",
      "nendoroid ",
      " nendoroid",
      "Good Smile Nendoroid",
      "GSC Nendoroid",
      "ねんどろいど",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  pricing: {
    name: "Figuras de Premio",
    slug: "pricing",
    description: "Figuras de anime de premio originales de Banpresto, Taito, Sega y más. Prize figures económicas con excelente relación calidad-precio para empezar tu colección. Más de 20 líneas diferentes. Importadas desde Japón para coleccionistas en Perú con envío gratis.",
    badge: "💰 Banpresto, Taito, Sega • Más de 20 líneas",
    iconName: "DollarSign",
    colors: {
      primary: "text-indigo-800",
      secondary: "text-indigo-600",
      gradient: "bg-gradient-to-b from-indigo-50 via-white to-purple-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-900",
      focus: "focus:ring-indigo-500",
    },
    searchTerms: [
      "Coreful",
      "Artist Masterpiece",
      "Luminasta",
      "Trio-Try-iT",
      "Banpresto Crane Games",
      "Petite World Memories",
      "Petite World Memories Mini Figure",
      "BiCute",
      "BiCute Bunnies",
      "BiCute Dark",
      "BiCute Ribbons",
      "BiCute Pure",
      "Hikkake",
      "Hikkake Figure",
      "Vivit",
      "Vivit Figure",
      "Relax time",
      "GLITTER & GLAMOURS",
      "VIBRATION STARS",
      "King of Artist",
      "SPM Figure",
      "Chokonose Premium",
      "Yumemirize",
      "Desktop",
      "Noodle Stopper",
      "Exc∞d Creative",
      "Sofvimates",
      "ESPRESTO",
      "PenLife!",
      "MAXIMATIC",
      "FiGURiZMα",
      "Break time collection",
      "T-most",
      "Banpresto",
      "BANPRESTO",
      "Taito",
      "TAITO",
      "Sega",
      "SEGA",
    ],
    brandTerms: [
      "Banpresto Crane Games",
      "Konami",
      "GiGO",
      "System Service",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },
}
