import type { CategoryConfig } from "@/types/category"

const commonSeries = [
  "One Piece",
  "Dragon Ball",
  "Boku no Hero Academia",
  "My Hero Academia",
  "Kimetsu no Yaiba",
  "Demon Slayer",
  "Gotoubun no Hanayome",
  "Quintessential Quintuplets",
  "Evangelion",
  "Jujutsu Kaisen",
  "Re:Zero",
  "SPY x FAMILY",
  "Spy Family",
  "Tensei Shitara Slime",
  "That Time I Got Reincarnated as a Slime",
  "Naruto",
  "Attack on Titan",
  "Shingeki no Kyojin",
  "Tokyo Revengers",
  "Chainsaw Man",
  "Bleach",
  "Hunter x Hunter",
  "Mob Psycho",
  "Overlord",
  "Konosuba",
  "Fate",
  "Hololive",
  "Vtuber",
  "Pokemon",
  "Digimon",
  "Sailor Moon",
  "Cardcaptor Sakura",
  "Love Live",
  "Idolmaster",
  "Vocaloid",
  "Hatsune Miku",
]

export const categoryConfigs: Record<string, CategoryConfig> = {
  scale: {
    name: "Scale Figures",
    slug: "scale",
    description: "Figuras a escala de máximo detalle y calidad",
    badge: "📏 Proporciones perfectas • Detalles excepcionales",
    iconName: "Ruler",
    colors: {
      primary: "text-emerald-800",
      secondary: "text-emerald-600",
      gradient: "bg-gradient-to-b from-emerald-50 via-white to-teal-50",
      focus: "focus:ring-emerald-500",
    },
    searchTerms: ["scale", "Scale", "SCALE", "1/7", "1/8", "1/6", "1/4"],
    searchType: "scale",
    seriesList: commonSeries,
  },

  figma: {
    name: "Figma",
    slug: "figma",
    description: "Figuras articuladas de máxima calidad y detalle",
    badge: "🔧 Articulación premium • Accesorios intercambiables",
    iconName: "Settings",
    colors: {
      primary: "text-blue-800",
      secondary: "text-blue-600",
      gradient: "bg-gradient-to-b from-blue-50 via-white to-cyan-50",
      focus: "focus:ring-blue-500",
    },
    searchTerms: [
      "Figma",
      "figma",
      "FIGMA",
      "figma ",
      " figma",
      "Figma ",
      " Figma",
      "Max Factory",
      "Good Smile Company figma",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  figuarts: {
    name: "S.H.Figuarts",
    slug: "figuarts",
    description: "Figuras de acción de élite con articulación perfecta",
    badge: "⚔️ Línea premium de Bandai • Articulación superior",
    iconName: "Sword",
    colors: {
      primary: "text-red-800",
      secondary: "text-red-600",
      gradient: "bg-gradient-to-b from-red-50 via-white to-yellow-50",
      focus: "focus:ring-red-500",
    },
    searchTerms: [
      "S.H.Figuarts",
      "s.h.figuarts",
      "S.H.FIGUARTS",
      "Figuarts",
      "figuarts",
      "FIGUARTS",
      "S.H. Figuarts",
      "SH Figuarts",
      "sh figuarts",
      "SHFiguarts",
      "Bandai Figuarts",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },
  ichiban: {
    name: "Ichiban Kuji",
    slug: "ichiban",
    description: "",
    badge: " ",
    iconName: "Gift",
    colors: {
      primary: "text-orange-800",
      secondary: "text-orange-600",
      gradient: "bg-gradient-to-b from-orange-50 via-white to-red-50",
      focus: "focus:ring-orange-500",
    },
    searchTerms: [
      "Ichiban Kuji",
      "ichiban kuji",
      "ICHIBAN KUJI",
      "Ichiban",
      "ichiban",
      "ICHIBAN",
      "Kuji",
      "kuji",
      "KUJI",
      "Banpresto Ichiban",
      "一番くじ",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  plush: {
    name: "Plushies",
    slug: "plush",
    description: "Peluches adorables y suaves para coleccionar",
    badge: "🧸 Materiales premium • Diseños kawaii",
    iconName: "Heart",
    colors: {
      primary: "text-pink-800",
      secondary: "text-pink-600",
      gradient: "bg-gradient-to-b from-pink-50 via-white to-rose-50",
      focus: "focus:ring-pink-500",
    },
    searchTerms: [
      "plush",
      "plushie",
      "Plush",
      "Plushie",
      "PLUSH",
      "PLUSHIE",
      "peluche",
      "Peluche",
      "PELUCHE",
      "stuffed",
      "Stuffed",
      "soft toy",
    ],
    searchType: "name",
    seriesList: [...commonSeries, "Pokemon", "Sanrio", "Hello Kitty", "Rilakkuma", "Pusheen"],
  },

  popup: {
    name: "Pop Up Parade",
    slug: "popup",
    description: "Figuras de alta calidad a precios accesibles",
    badge: "⚡ Línea premium de Good Smile Company • Calidad excepcional",
    iconName: "Zap",
    colors: {
      primary: "text-purple-800",
      secondary: "text-purple-600",
      gradient: "bg-gradient-to-b from-purple-50 via-white to-pink-50",
      focus: "focus:ring-purple-500",
    },
    searchTerms: [
      "Pop Up Parade",
      "pop up parade",
      "POP UP PARADE",
      "PopUp Parade",
      "popup parade",
      "POPUP PARADE",
      "Pop-Up Parade",
      "pop-up parade",
      "Good Smile Pop Up",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  nendoroid: {
    name: "Nendoroid",
    slug: "nendoroid",
    description: "Figuras chibi adorables y coleccionables",
    badge: "😊 Diseño kawaii • Partes intercambiables • Expresiones múltiples",
    iconName: "Smile",
    colors: {
      primary: "text-yellow-800",
      secondary: "text-yellow-600",
      gradient: "bg-gradient-to-b from-yellow-50 via-white to-orange-50",
      focus: "focus:ring-yellow-500",
    },
    searchTerms: [
      "Nendoroid",
      "nendoroid",
      "NENDOROID",
      "Nendoroid ",
      " Nendoroid",
      "nendoroid ",
      " nendoroid",
      "Good Smile Nendoroid",
      "GSC Nendoroid",
      "ねんどろいど",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },

  pricing: {
    name: "Figuras Pricing",
    slug: "pricing",
    description: "Figuras de líneas premium con excelente relación calidad-precio",
    badge: "💰 Líneas premium con excelente relación calidad-precio • Más de 20 líneas disponibles",
    iconName: "DollarSign",
    colors: {
      primary: "text-green-800",
      secondary: "text-green-600",
      gradient: "bg-gradient-to-b from-green-50 via-white to-emerald-50",
      focus: "focus:ring-green-500",
    },
    searchTerms: [
      "Coreful",
      "Artist Masterpiece",
      "Luminasta",
      "Trio-Try-iT",
      "BiCute Bunnies",
      "BiCute Dark",
      "Relax time",
      "GLITTER & GLAMOURS",
      "VIBRATION STARS",
      "King of Artist",
      "SPM Figure",
      "Chokonose Premium",
      "Yumemirize",
      "Desktop",
      "Noodle Stopper",
      "Exc∞d Creative",
      "Sofvimates",
      "ESPRESTO",
      "PenLife!",
      "MAXIMATIC",
      "FiGURiZMα",
      "Break time collection",
      "T-most",
      "Banpresto",
      "BANPRESTO",
      "Taito",
      "TAITO",
      "Sega",
      "SEGA",
    ],
    searchType: "line",
    seriesList: commonSeries,
  },
}
